import Link from "next/link";
import { Plus } from "lucide-react";
import { AssignmentActions } from "@/app/admin/assignments/assignment-actions";
import { requireAdmin } from "@/src/server/auth";
import { assignmentListSchema, listAssignments } from "@/src/server/services/tasks";

export const dynamic = "force-dynamic";

export default async function AssignmentsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const viewer = await requireAdmin();
  const params = await searchParams;
  const query = assignmentListSchema.parse({ search: typeof params.search === "string" && params.search ? params.search : undefined, status: typeof params.status === "string" && params.status ? params.status : undefined, cursor: typeof params.cursor === "string" && params.cursor ? params.cursor : undefined, limit: 25 });
  const result = await listAssignments(viewer, query);
  return <main className="px-5 py-8 sm:px-10"><header className="flex flex-wrap items-end justify-between gap-6 border-b border-[var(--line)] pb-7"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--teal)]">Frozen task delivery</p><h1 className="display mt-2 text-5xl font-semibold">Assignments</h1></div><Link href="/admin/assignments/new" className="inline-flex items-center gap-2 bg-[var(--signal)] px-5 py-3 font-bold text-white"><Plus className="h-4 w-4" />创建 Assignment</Link></header><form className="my-7 flex gap-3 border border-[var(--line)] bg-white/30 p-3"><input name="search" defaultValue={query.search} placeholder="Assignment / Participant / Task" className="min-w-0 flex-1 border border-[var(--line)] bg-[var(--paper)] px-4 py-3" /><select name="status" defaultValue={query.status || ""} className="border border-[var(--line)] bg-[var(--paper)] px-3"><option value="">全部状态</option>{["assigned","acknowledged","session_created","uploading","submitted","needs_review","rework_required","accepted","expired","missing_upload","canceled"].map((status) => <option key={status} value={status}>{status}</option>)}</select><button className="bg-[var(--ink)] px-5 py-3 font-bold text-[var(--paper)]">筛选</button></form><div className="grid gap-4 xl:grid-cols-2">{result.items.map((assignment) => <article key={assignment.publicId} className="border border-[var(--line)] bg-white/35 p-6"><div className="flex flex-wrap justify-between gap-3"><p className="text-xs font-bold text-[var(--signal)]">{assignment.publicId}</p><div className="flex gap-2"><span className="text-xs font-bold uppercase">{assignment.status}</span>{assignment.isMissing ? <span className="bg-[var(--yellow)] px-2 text-xs font-bold">Missing</span> : null}</div></div><h2 className="display mt-4 text-2xl font-semibold">{assignment.taskTitle} · v{assignment.taskVersion}</h2><p className="mt-3 text-sm">{assignment.participantAlias} · {assignment.participantPublicId}</p><p className="mt-2 text-xs text-[var(--muted)]">Due {assignment.dueAt.toLocaleString("zh-CN")} · {assignment.studyPublicId}</p><AssignmentActions assignmentPublicId={assignment.publicId} status={assignment.status} /></article>)}</div>{result.items.length === 0 ? <p className="py-12 text-center text-sm text-[var(--muted)]">尚无 Assignment。</p> : null}</main>;
}
