import Link from "next/link";
import { SessionClose } from "@/app/admin/sessions/session-close";
import { requireAdmin } from "@/src/server/auth";
import { adminSessionListSchema, listAdminSessions } from "@/src/server/services/sessions";

export const dynamic = "force-dynamic";

export default async function AdminSessionsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const viewer = await requireAdmin();
  const params = await searchParams;
  const query = adminSessionListSchema.parse({ search: typeof params.search === "string" && params.search ? params.search : undefined, status: typeof params.status === "string" && params.status ? params.status : undefined, cursor: typeof params.cursor === "string" && params.cursor ? params.cursor : undefined, limit: 50 });
  const result = await listAdminSessions(viewer, query);
  const next = new URLSearchParams({ ...(query.search ? { search: query.search } : {}), ...(query.status ? { status: query.status } : {}), ...(result.nextCursor ? { cursor: result.nextCursor } : {}) });
  return <main className="px-5 py-8 sm:px-10"><header className="border-b border-[var(--line)] pb-7"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--teal)]">Declared recording context</p><h1 className="display mt-2 text-5xl font-semibold">Recording Sessions</h1></header><form className="my-7 flex flex-wrap gap-3 border border-[var(--line)] bg-white/30 p-3"><input name="search" defaultValue={query.search} placeholder="Session / Assignment / Participant / Task" className="min-w-64 flex-1 border border-[var(--line)] bg-[var(--paper)] px-3 py-3" /><select name="status" aria-label="Session Status" defaultValue={query.status ?? ""} className="border border-[var(--line)] bg-[var(--paper)] px-3"><option value="">全部状态</option><option value="open">open</option><option value="closed">closed</option></select><button className="bg-[var(--ink)] px-5 py-3 font-bold text-[var(--paper)]">筛选</button></form><div className="grid gap-4 xl:grid-cols-2">{result.items.map((session) => <article key={session.publicId} className="border border-[var(--line)] bg-white/35 p-6"><div className="flex justify-between gap-4"><p className="text-xs font-bold text-[var(--signal)]">{session.publicId}</p><span className="text-xs font-bold uppercase">{session.status}</span></div><h2 className="display mt-4 text-2xl font-semibold">{session.taskTitle}</h2><p className="mt-3 text-sm">{session.participantAlias} · {session.participantPublicId}</p><p className="mt-2 text-xs text-[var(--muted)]">{session.deviceLabel} · {session.devicePublicId}</p><p className="mt-2 text-xs text-[var(--muted)]">Marker {session.markerAcknowledgedAt ? "已确认" : "待确认"} · {session.createdAt.toLocaleString("zh-CN")}</p>{session.status === "open" ? <SessionClose sessionPublicId={session.publicId} /> : null}</article>)}{result.items.length === 0 ? <p className="text-sm text-[var(--muted)]">尚无 Recording Session。</p> : null}</div>{result.nextCursor ? <Link href={`?${next.toString()}`} className="mt-8 inline-block font-bold text-[var(--teal)]">下一页 →</Link> : null}</main>;
}
